### PR TITLE
Fixed catalog is downloaded twice on startup

### PR DESCRIPTION
**Pull request by tmancey**
fixes https://github.com/brave-intl/bat-native-ads/issues/68

### CODE REVIEW

**Comment by bridiver** [comment]
Is the catalog always downloaded on browser startup? That's a privacy issue if it is. We obviously need to download when ads is enabled, but after that it should happen on a randomized schedule

**Comment by tmancey** [comment]
Catalog is downloaded on browser start as if the catalog is out of date then tokens for confirmations could fail to redeem

**Comment by bridiver** [comment]
@tmancey we just can't do that for privacy reasons because it becomes a proxy for browser usage. I'm going to open a ticket for it.

**Comment by tmancey** [comment]
Sure let’s raise with jimmy and security team so we can try to unblock ASAP

**Pull request merged**
